#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xF7F9B0A300C1B70D (releases@openinfosecfoundation.org)
#
Name     : suricata
Version  : 4.0.5
Release  : 14
URL      : https://www.openinfosecfoundation.org/download/suricata-4.0.5.tar.gz
Source0  : https://www.openinfosecfoundation.org/download/suricata-4.0.5.tar.gz
Source99 : https://www.openinfosecfoundation.org/download/suricata-4.0.5.tar.gz.sig
Summary  : A security-aware HTTP parser, designed for use in IDS/IPS and WAF products.
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0 MIT
Requires: suricata-bin
Requires: suricata-python3
Requires: suricata-config
Requires: suricata-lib
Requires: suricata-license
Requires: suricata-man
Requires: suricata-python
BuildRequires : Sphinx
BuildRequires : buildreq-distutils3
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : hyperscan-dev
BuildRequires : jansson-dev
BuildRequires : libcap-ng-dev
BuildRequires : libpcap-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pkgconfig(libhs)
BuildRequires : pkgconfig(libnetfilter_queue)
BuildRequires : pkgconfig(libpcre)
BuildRequires : pkgconfig(lua)
BuildRequires : pkgconfig(luajit)
BuildRequires : pkgconfig(nspr)
BuildRequires : pkgconfig(nss)
BuildRequires : pkgconfig(zlib)
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : yaml-dev

%description


%package bin
Summary: bin components for the suricata package.
Group: Binaries
Requires: suricata-config
Requires: suricata-license
Requires: suricata-man

%description bin
bin components for the suricata package.


%package config
Summary: config components for the suricata package.
Group: Default

%description config
config components for the suricata package.


%package dev
Summary: dev components for the suricata package.
Group: Development
Requires: suricata-lib
Requires: suricata-bin
Provides: suricata-devel

%description dev
dev components for the suricata package.


%package doc
Summary: doc components for the suricata package.
Group: Documentation
Requires: suricata-man

%description doc
doc components for the suricata package.


%package lib
Summary: lib components for the suricata package.
Group: Libraries
Requires: suricata-license

%description lib
lib components for the suricata package.


%package license
Summary: license components for the suricata package.
Group: Default

%description license
license components for the suricata package.


%package man
Summary: man components for the suricata package.
Group: Default

%description man
man components for the suricata package.


%package python
Summary: python components for the suricata package.
Group: Default
Requires: suricata-python3

%description python
python components for the suricata package.


%package python3
Summary: python3 components for the suricata package.
Group: Default
Requires: python3-core

%description python3
python3 components for the suricata package.


%prep
%setup -q -n suricata-4.0.5
pushd ..
cp -a suricata-4.0.5 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1531919923
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=haswell"
export CXXFLAGS="$CXXFLAGS -m64 -march=haswell"
export LDFLAGS="$LDFLAGS -m64 -march=haswell"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1531919923
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/suricata
cp COPYING %{buildroot}/usr/share/doc/suricata/COPYING
cp LICENSE %{buildroot}/usr/share/doc/suricata/LICENSE
cp libhtp/LICENSE %{buildroot}/usr/share/doc/suricata/libhtp_LICENSE
cp contrib/file_processor/LICENSE %{buildroot}/usr/share/doc/suricata/contrib_file_processor_LICENSE
cp contrib/tile_pcie_logd/LICENSE %{buildroot}/usr/share/doc/suricata/contrib_tile_pcie_logd_LICENSE
cp rust/vendor/lazy_static/LICENSE-MIT %{buildroot}/usr/share/doc/suricata/rust_vendor_lazy_static_LICENSE-MIT
cp rust/vendor/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/doc/suricata/rust_vendor_lazy_static_LICENSE-APACHE
cp rust/vendor/libc/LICENSE-MIT %{buildroot}/usr/share/doc/suricata/rust_vendor_libc_LICENSE-MIT
cp rust/vendor/libc/LICENSE-APACHE %{buildroot}/usr/share/doc/suricata/rust_vendor_libc_LICENSE-APACHE
cp rust/vendor/ntp-parser/LICENSE-APACHE %{buildroot}/usr/share/doc/suricata/rust_vendor_ntp-parser_LICENSE-APACHE
cp rust/vendor/nom/LICENSE %{buildroot}/usr/share/doc/suricata/rust_vendor_nom_LICENSE
pushd ../buildavx2/
%make_install_avx2
popd
%make_install
## make_install_append content
install -m 0644 -D etc/suricata.service %{buildroot}/usr/lib/systemd/system/suricata.service
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/haswell/suricata
/usr/bin/suricata
/usr/bin/suricatasc

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/suricata.service

%files dev
%defattr(-,root,root,-)
/usr/include/htp/bstr.h
/usr/include/htp/bstr_builder.h
/usr/include/htp/htp.h
/usr/include/htp/htp_base64.h
/usr/include/htp/htp_config.h
/usr/include/htp/htp_connection_parser.h
/usr/include/htp/htp_core.h
/usr/include/htp/htp_decompressors.h
/usr/include/htp/htp_hooks.h
/usr/include/htp/htp_list.h
/usr/include/htp/htp_multipart.h
/usr/include/htp/htp_table.h
/usr/include/htp/htp_transaction.h
/usr/include/htp/htp_urlencoded.h
/usr/include/htp/htp_utf8_decoder.h
/usr/include/htp/htp_version.h
/usr/lib64/haswell/libhtp.so
/usr/lib64/libhtp.so
/usr/lib64/pkgconfig/htp.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/suricata/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/haswell/libhtp.so.2
/usr/lib64/haswell/libhtp.so.2.0.0
/usr/lib64/libhtp.so.2
/usr/lib64/libhtp.so.2.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/suricata/COPYING
/usr/share/doc/suricata/LICENSE
/usr/share/doc/suricata/contrib_file_processor_LICENSE
/usr/share/doc/suricata/contrib_tile_pcie_logd_LICENSE
/usr/share/doc/suricata/libhtp_LICENSE
/usr/share/doc/suricata/rust_vendor_lazy_static_LICENSE-APACHE
/usr/share/doc/suricata/rust_vendor_lazy_static_LICENSE-MIT
/usr/share/doc/suricata/rust_vendor_libc_LICENSE-APACHE
/usr/share/doc/suricata/rust_vendor_libc_LICENSE-MIT
/usr/share/doc/suricata/rust_vendor_nom_LICENSE
/usr/share/doc/suricata/rust_vendor_ntp-parser_LICENSE-APACHE

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/suricata.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
